# Generated by Django 5.0.6 on 2024-05-17 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pelanggaran_siswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pelanggaran',
            name='catatan',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pelanggaran',
            name='poin',
            field=models.IntegerField(),
        ),
    ]
